### ISSUE TITLE
ci_launcher.py explodes when a board is no longer available

### ISSUE THREAD

**Issue by tpetazzoni** [free-electrons/custom_tests_tool#7]
The armada-385-db-ap has been recently removed from our infra, but we still have some tests listed for it in ci_tests.json, and this makes ci_launcher.py explode:

```
ctt@lava:~/custom_tests_tool$ ./ci_launcher.py -b armada-385-db-ap
armada-385-db-ap
  Making crypto job on mainline -> master -> multi_v7_defconfig
    Notifications recipients: 
    Root filesystem path: http://lava.free-electrons.com/downloads/rootfs/rootfs_armv7.cpio.gz
    Kernel path: https://storage.kernelci.org//mainline/master/v4.15-rc4-304-gd1f854ac240e/arm/multi_v7_defconfig/zImage
    Device tree path: https://storage.kernelci.org//mainline/master/v4.15-rc4-304-gd1f854ac240e/arm/multi_v7_defconfig/dtbs/armada-385-db-ap.dtb
    Modules archive path: https://storage.kernelci.org//mainline/master/v4.15-rc4-304-gd1f854ac240e/arm/multi_v7_defconfig/modules.tar.xz
Traceback (most recent call last):
  File "./ci_launcher.py", line 93, in <module>
    CILauncher().launch()
  File "./ci_launcher.py", line 90, in launch
    self.crafter.make_jobs(board, artifacts, test['name'], job_name)
  File "/home/ctt/custom_tests_tool/src/crafter.py", line 149, in make_jobs
    self.job_template.render(self.job))
  File "/home/ctt/custom_tests_tool/src/writers.py", line 100, in write
    ret = self._con.scheduler.submit_job(job)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 400: 'Device unavailable: No devices of type armada-385-db-ap are currently available to user custom-tests'>
```

Instead ci_launcher should gracefully ignore this issue, and continue with the next board.

**Comment by MyleneJ** [comment]
Closed with commit [4d5b4ef](https://github.com/free-electrons/custom_tests_tool/commit/4d5b4ef574327041ff07f487c97856fec6e2d6a4).
